package mwp.domain;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="hehe")
public class Hehe {
    @Basic
    private String desciption;

    @Basic
    private String description;

    @Basic
    private String extend;

    @Id
    private long id;


    public Hehe() {
    }

    public Hehe(long id) {
        this.id = id;
    }

    public String getDesciption() {
        return desciption;
    }

    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getExtend() {
        return extend;
    }

    public void setExtend(String extend) {
        this.extend = extend;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}